### ISSUE TITLE
Keys sorting

### ISSUE THREAD

**Issue by maxkonovalov** [wleii/TrickerX#1]
Hi @wleii! Thanks for the extension, it is really useful!
What do you think of keeping the generated CodingKeys ordered the same as the originally declared variables, rather than sorting them alphabetically? I think that would make more sense :)

**Comment by wleii** [comment]
@maxkonovalov Thanks
I agree with what you said. My initial idea was just to make it look more neat and easy to find the key..

**Comment by maxkonovalov** [comment]
Hi @wleii 
Just saw that you closed the issue - are you still going to add an option to disable the sorting? Having the keys sorted gets really gets into the way for me.

**Comment by wleii** [comment]
Hi @maxkonovalov 
I just release the new dmg version, it’s append a new command that help you sorting (or not) the keys.
Thanks your propose :)

**Comment by maxkonovalov** [comment]
That's great! Thank you very much 👏
