### ISSUE TITLE
add new CodingKey

### ISSUE THREAD

**Issue by MMnasrabadi** [wleii/TrickerX#4]
please add new CodingKey
:  capitalize first letter of each word

like: 

struct CreatePasscodeModel: CodablePro {
    let passcode: String?
    let verifyCode: String?

    private enum CodingKeys: String, CodingKey {
        case passcode = "Passcode"
        case verifyCode = "VerifyCode"
    }
}

**Comment by wleii** [comment]
This project accepts contributed code, you can implement this feature, I will merge it,  thx :]
